FROM node:10-alpine
MAINTAINER Rindi Ismail "rindiismail@gmail.com"

COPY . /usr/src/app
WORKDIR /usr/src/app

ENV NODE_ENV dev

RUN npm install -g @angular/cli

EXPOSE 80

# run with http
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "80"]

# run with https
# CMD ["ng", "serve", "--host", "0.0.0.0", "--ssl", "true", "--ssl-cert", "/usr/src/app/localhost-ssl.crt", "--ssl-key", "/usr/src/app/localhost-ssl.key"]